---
DOWN: 
  drop_tables: 
    - features
    - display_features
UP: 
  create_tables: 
    features: 
      name: 
        type: string
        default: false
        length: 50
        - not_null
    display_features:
      display_id: 
        type: integer
        default: false
        length: 11
        - not_null
      feature_id: 
        type: integer
        default: false
        length: 11
        - not_null
